### ISSUE TITLE
Not working with the terminal version of Spacemacs

### ISSUE THREAD

**Issue by tofuya** [emacs-origami/origami.el#34]
#### Description :octocat:
Not working with the terminal version of Spacemacs.

#### Reproduction guide :beetle:
- Fix .spacemacs to
```
dotspacemacs-additional-packages '((origami :location (recipe :fetcher github :repo "emacs-origami/origami.el")))
```
```
dotspacemacs-folding-method 'origami
```
- Start Spacemacs
- Open a text file
- Press zm

*Observed behaviour:* :eyes: :broken_heart:
The code is not folded

#### System Info :computer:
- Origami version: 20210509.0
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 37c8669d3)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM NS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  origami-rebuild-tree\?(#<buffer REPORT_SPACEMACS_ISSUE<2>>)
  origami-get-fold-tree(#<buffer REPORT_SPACEMACS_ISSUE<2>>)
  origami-close-all-nodes(#<buffer REPORT_SPACEMACS_ISSUE<2>>)
  funcall-interactively(origami-close-all-nodes #<buffer REPORT_SPACEMACS_ISSUE<2>>)
  call-interactively(origami-close-all-nodes nil nil)
  command-execute(origami-close-all-nodes)
```

**Comment by jcs090218** [comment]
Can you paste the code your were trying to fold? Thanks!

**Comment by tofuya** [comment]
Thank you for your reply. Here is the text file I tried.
```
foo
  bar
baz
```

**Comment by jcs090218** [comment]
Okay, I have applied a patch in f53bf717e75f0957d454f8236ec176d471ff7e9b with better defense programming strategy.

Are you trying to fold in the `text-mode`? You might see warning like. 😕 

```
[WARNING] No parser specify in major-mode, ‘text-mode‘
```

**Comment by tofuya** [comment]
Yes, it is in text mode. And I have checked the warning message.
However, in gregsexton's origami, if the parser to be used in major-mode is not specified, origami-indent-parser seems to be used, and folding in text files is possible.
For convenience, it may be better to make it work with emacs-origami as well.

**Comment by jcs090218** [comment]
Ah, okay. I have revert changes so the default will always be the indent parser. Thanks! 👍

**Comment by jcs090218** [comment]
Does the patch resolved the original issue `(wrong-type-argument number-or-marker-p nil)`? If it does, I guess this issue can be closed?

**Comment by jcs090218** [comment]
I assumed the issue can be closed? Feel free to reopen this issue if you find out useful! :)
