### ISSUE TITLE
Folding overlay disappear after command `eval-buffer`

### ISSUE THREAD

**Issue by jcs090218** [emacs-origami/origami.el#4]
This only happens when evaluable buffer, like `emacs-lisp-mode` or `lisp-interaction-mode`.

Steps to reproduce:

1. Fold a node.
2. `M-x eval-buffer`

**Comment by mosquito-magnet** [comment]
I tried this, but works fine on my setup in both modes

**Comment by jcs090218** [comment]
Ah, you are right. I guess this somehow goes away. Thanks! :)
